/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	schedulingv1beta1 "volcano.sh/apis/pkg/apis/scheduling/v1beta1"
)

// DeviceTopologyDomainSelectorApplyConfiguration represents a declarative configuration of the DeviceTopologyDomainSelector type for use
// with apply.
//
// DeviceTopologyDomainSelector selects a catalog-defined class of topology domains.
type DeviceTopologyDomainSelectorApplyConfiguration struct {
	// Scope specifies whether the selected domain is node-local or fabric-wide.
	Scope *schedulingv1beta1.DeviceTopologyDomainScope `json:"scope,omitempty"`
	// DomainClass is the stable catalog name of the requested topology domain class.
	DomainClass *schedulingv1beta1.DeviceTopologyDomainClass `json:"domainClass,omitempty"`
}

// DeviceTopologyDomainSelectorApplyConfiguration constructs a declarative configuration of the DeviceTopologyDomainSelector type for use with
// apply.
func DeviceTopologyDomainSelector() *DeviceTopologyDomainSelectorApplyConfiguration {
	return &DeviceTopologyDomainSelectorApplyConfiguration{}
}

// WithScope sets the Scope field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Scope field is set to the value of the last call.
func (b *DeviceTopologyDomainSelectorApplyConfiguration) WithScope(value schedulingv1beta1.DeviceTopologyDomainScope) *DeviceTopologyDomainSelectorApplyConfiguration {
	b.Scope = &value
	return b
}

// WithDomainClass sets the DomainClass field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DomainClass field is set to the value of the last call.
func (b *DeviceTopologyDomainSelectorApplyConfiguration) WithDomainClass(value schedulingv1beta1.DeviceTopologyDomainClass) *DeviceTopologyDomainSelectorApplyConfiguration {
	b.DomainClass = &value
	return b
}
