/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
	schedulingv1beta1 "volcano.sh/apis/pkg/apis/scheduling/v1beta1"
)

// DeviceTopologyPolicyApplyConfiguration represents a declarative configuration of the DeviceTopologyPolicy type for use
// with apply.
//
// DeviceTopologyPolicy describes device topology intent for one extended resource.
type DeviceTopologyPolicyApplyConfiguration struct {
	// ResourceName is the qualified name of the extended resource governed by this policy.
	ResourceName *v1.ResourceName `json:"resourceName,omitempty"`
	// ApplyTo specifies the scheduling unit affected by this policy. Defaults to Pod.
	ApplyTo *schedulingv1beta1.DeviceTopologyApplyTo `json:"applyTo,omitempty"`
	// Mode specifies whether this policy is a hard constraint or a soft preference. Defaults to hard.
	Mode *schedulingv1beta1.DeviceTopologyMode `json:"mode,omitempty"`
	// Domain selects the requested class of topology domains.
	Domain *DeviceTopologyDomainSelectorApplyConfiguration `json:"domain,omitempty"`
	// PodSelector optionally narrows a PodGroup-level Pod policy to matching Pods.
	PodSelector *metav1.LabelSelectorApplyConfiguration `json:"podSelector,omitempty"`
}

// DeviceTopologyPolicyApplyConfiguration constructs a declarative configuration of the DeviceTopologyPolicy type for use with
// apply.
func DeviceTopologyPolicy() *DeviceTopologyPolicyApplyConfiguration {
	return &DeviceTopologyPolicyApplyConfiguration{}
}

// WithResourceName sets the ResourceName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceName field is set to the value of the last call.
func (b *DeviceTopologyPolicyApplyConfiguration) WithResourceName(value v1.ResourceName) *DeviceTopologyPolicyApplyConfiguration {
	b.ResourceName = &value
	return b
}

// WithApplyTo sets the ApplyTo field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ApplyTo field is set to the value of the last call.
func (b *DeviceTopologyPolicyApplyConfiguration) WithApplyTo(value schedulingv1beta1.DeviceTopologyApplyTo) *DeviceTopologyPolicyApplyConfiguration {
	b.ApplyTo = &value
	return b
}

// WithMode sets the Mode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mode field is set to the value of the last call.
func (b *DeviceTopologyPolicyApplyConfiguration) WithMode(value schedulingv1beta1.DeviceTopologyMode) *DeviceTopologyPolicyApplyConfiguration {
	b.Mode = &value
	return b
}

// WithDomain sets the Domain field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Domain field is set to the value of the last call.
func (b *DeviceTopologyPolicyApplyConfiguration) WithDomain(value *DeviceTopologyDomainSelectorApplyConfiguration) *DeviceTopologyPolicyApplyConfiguration {
	b.Domain = value
	return b
}

// WithPodSelector sets the PodSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodSelector field is set to the value of the last call.
func (b *DeviceTopologyPolicyApplyConfiguration) WithPodSelector(value *metav1.LabelSelectorApplyConfiguration) *DeviceTopologyPolicyApplyConfiguration {
	b.PodSelector = value
	return b
}
