apiVersion: v1
kind: ConfigMap
metadata:
  name: volcano-scheduler-configmap
  namespace: volcano-system
data:
  volcano-scheduler.conf: |
    actions: "enqueue, allocate, backfill"
    tiers:
    - plugins:
      - name: priority
      - name: gang
      - name: conformance
    - plugins:
      - name: drf
      - name: predicates
      - name: deviceshare
        arguments:
          deviceshare.VGPUEnable: true
          deviceshare.SchedulePolicy: binpack
          deviceshare.ScheduleWeight: 10
      - name: proportion
      - name: nodeorder
      - name: binpack
        arguments:
          binpack.resources: volcano.sh/vgpu-number,volcano.sh/vgpu-memory,volcano.sh/vgpu-cores
          binpack.resources.volcano.sh/vgpu-number: 1
          binpack.resources.volcano.sh/vgpu-memory: 5
          binpack.resources.volcano.sh/vgpu-cores: 2
