kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
  - role: worker
    labels:
      nvml-mock/profile: h100
      nvidia.com/gpu.present: "true"
      xpu01b-probe/node: gpu
